[workspace]
members = [
    'node',
    'pallets/poa',
#    'pallets/accounting',
    'runtime',
]

#[features]
#runtime-benchmarks = [
#	"runtime/runtime-benchmarks",
#]

[profile.release]
panic = 'unwind'