[dependencies.aura]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-aura'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-balances'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-executive]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.frame-support]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-grandpa'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.randomness-collective-flip]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-randomness-collective-flip'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-consensus-aura]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '0.8.0-rc2'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-offchain]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-session]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-std]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sp-version]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.sudo]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-sudo'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.system]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'frame-system'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.timestamp]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-timestamp'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[dependencies.transaction-payment]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'pallet-transaction-payment'
tag = 'v2.0.0-rc2'
version = '2.0.0-rc2'

[build-dependencies.wasm-builder-runner]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-wasm-builder-runner'
tag = 'v2.0.0-rc2'
version = '1.0.5'

[features]
default = ['std']
std = [
    'aura/std',
    'balances/std',
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'grandpa/std',
    'randomness-collective-flip/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'sudo/std',
    'system/std',
    'timestamp/std',
    'transaction-payment/std',
]

[dev-dependencies]
rand = "0.7.3"

[package]
authors = ['Dock.io']
edition = '2018'
name = 'dock-testnet-runtime'
version = '2.0.0-rc2'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
